#!/bin/bash

export THIS_SCRIPT=$(basename "$0")

if [ "$#" -ne 1 ]; then
    echo "Usage: $THIS_SCRIPT <target@host>:<path>"
    echo "Backups up home directories with django subdirectory"
    echo "Excludes files starting with '.', and directories logs and venv"
    echo "Run this script only on remote"
    exit 1
fi

export TARGET=$1
echo "Backing Django users to $TARGET"

for f in /home/*; do
    u=`basename $f`
    if [ -d "$f/django" ]; then
        echo "Backing up $f to $TARGET"
        rsync -aP --exclude 'logs' --exclude '__pycache__' --exclude 'venv' --exclude '.*' $f $TARGET
        rsync -aP "$f/django/project/settings.py" "$TARGET/$u-settings.py"
        if [ -f "$f/django/project/.env" ]; then
            rsync -aP "$f/django/project/.env" "$TARGET/$u.env"
        fi
        if [ -d "$f/logs" ]; then
            rsync -aP --exclude django.log --exclude uwsgi.log --exclude huey.log "$f/logs" "$TARGET"
        fi
    fi
done
