#!/bin/bash

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
sudo systemctl stop nginx
sudo certbot renew -q
sudo systemctl start nginx
