#!/bin/bash

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

systemctl status nginx
NGINX_STATUS="$?"

if [ "$NGINX_STATUS" == "0" ]; then
    systemctl stop nginx
fi

certbot renew --non-interactive

if [ "$NGINX_STATUS" == "0" ]; then
    systemctl start nginx
fi
