#!/bin/bash

if [ -f "$1" ] || [ ! -z "$2" ]; then
    echo "Removes specific line number from a file (modifies file)"
    echo "Usage: cutline <filename> <line number>"
    exit 1
fi

sed -i "${2}d" "${1}"
