#!/bin/bash

export THIS_SCRIPT=$(basename "$0")

if [ "$#" -lt 1 ]; then
    echo "Usage: $THIS_SCRIPT <path>"
    echo "$THIS_SCRIPT # of arguments was $#"
    exit 1
fi

if [[ "$1" = /* ]]; then
    echo "$1 is absolute path"
    exit 0
else
    echo "$1 is not absolute path"
    exit 1
fi
