#!/bin/bash

export BACKUP_DIR=`realpath "$1"`
if [ -z "$BACKUP_DIR" ]; then
    echo "usage: <backup dir>"
    exit 1
fi

TIMESTAMP=$(date +"%F")
mkdir -p $BACKUP_DIR

databases=`mariadb -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema)"`

for db in $databases; do
  echo "Backing up $db to $BACKUP_DIR/$db.sql.gz"
  mysqldump --force --opt --databases $db | gzip > "$BACKUP_DIR/$db.sql.gz"
done
