#!/bin/bash

if [ -z "$MARIADB_HOST" ] || [ -z "MARIADB_ROOT_USER" ] || [ -z "MARIADB_ROOT_PASSWORD" ]; then
    echo "MARIADB_HOST/MARIADB_ROOT_USER/MARIADB_ROOT_PASSWORD not set:"
    echo "export MARIADB_HOST="
    echo "export MARIADB_ROOT_USER=root"
    echo "export MARIADB_ROOT_PASSWORD=dev"
    exit 1
fi

mariadb --host "$MARIADB_HOST" --user "$MARIADB_ROOT_USER" --password="$MARIADB_ROOT_PASSWORD" $*
exit "$?"
