#!/bin/bash

USE_SOCKET=0
if [ -z "$MARIADB_HOST" ] || [ -z "MARIADB_ROOT_USER" ] || [ -z "MARIADB_ROOT_PASSWORD" ]; then
    echo "MARIADB_HOST, MARIADB_ROOT_USER and MARIADB_ROOT_PASSWORD not set, using socket connection"
    USE_SOCKET=1
fi

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: <dbfile.sql.gz> <dbname> <optional: pass>"
    exit 1
fi

dbfile="$1"
dbname="$2"
dbuser="$dbname"
dbpass="`tr -cd '[:alnum:]' < /dev/urandom | fold -w16 | head -n1`"
if [ ! -z "$3" ]; then
    dbpass="$3"
fi
dbhost="$MARIADB_HOST"

# Drop old DB if exists
echo "Dropping old DB $dbname if exists"
if [ "$USE_SOCKET" == "1" ]; then
    mariadb -e "SET @@SQL_MODE = ''; DROP DATABASE IF EXISTS $dbname;"
else
    mariadb --host "$MARIADB_HOST" --user "$MARIADB_ROOT_USER" --password="$MARIADB_ROOT_PASSWORD" -e "SET @@SQL_MODE = ''; DROP DATABASE IF EXISTS $dbname;"
fi

# Drop old user if exists
echo "Dropping old user $dbuser if exists"
if [ "$USE_SOCKET" == "1" ]; then
    mariadb -e "SET @@SQL_MODE = ''; DROP USER IF EXISTS '$dbname'@'$dbhost';"
else
    mariadb --host "$MARIADB_HOST" --user "$MARIADB_ROOT_USER" --password="$MARIADB_ROOT_PASSWORD" -e "SET @@SQL_MODE = ''; DROP USER IF EXISTS '$dbname'@'$dbhost';"
fi

# Create new DB
echo "Creating new DB $dbname"
if [ "$USE_SOCKET" == "1" ]; then
    mariadb -e "SET @@SQL_MODE = ''; CREATE DATABASE $dbname DEFAULT CHARACTER SET utf8;"
else
    mariadb --host "$MARIADB_HOST" --user "$MARIADB_ROOT_USER" --password="$MARIADB_ROOT_PASSWORD" -e "SET @@SQL_MODE = ''; CREATE DATABASE $dbname DEFAULT CHARACTER SET utf8;"
fi

# Create new user
echo "Creating new user $dbuser with password '$dbpass'"
if [ "$USE_SOCKET" == "1" ]; then
    mariadb -e "SET @@SQL_MODE = ''; CREATE USER '$dbuser'@'%' IDENTIFIED BY '$dbpass';"
    mariadb -e "SET @@SQL_MODE = ''; GRANT USAGE ON *.* TO '$dbuser'@'%';"
    mariadb -e "SET @@SQL_MODE = ''; GRANT ALL PRIVILEGES ON $dbname.* TO '$dbuser'@'%';"
else
    mariadb --host "$MARIADB_HOST" --user "$MARIADB_ROOT_USER" --password="$MARIADB_ROOT_PASSWORD" -e "SET @@SQL_MODE = ''; CREATE USER '$dbuser'@'%' IDENTIFIED BY '$dbpass';"
    mariadb --host "$MARIADB_HOST" --user "$MARIADB_ROOT_USER" --password="$MARIADB_ROOT_PASSWORD" -e "SET @@SQL_MODE = ''; GRANT USAGE ON *.* TO '$dbuser'@'%';"
    mariadb --host "$MARIADB_HOST" --user "$MARIADB_ROOT_USER" --password="$MARIADB_ROOT_PASSWORD" -e "SET @@SQL_MODE = ''; GRANT ALL PRIVILEGES ON $dbname.* TO '$dbuser'@'%';"
fi

# Preprocess: Skip foreign key checks for import and import with most relaxed SQL-mode
echo "Preprocessing: Skip foreign key checks for import and import with most relaxed SQL-mode"
tmpfile1="`tempfile`"
echo "SET @@SQL_MODE = ''; SET foreign_key_checks = 0;" > $tmpfile1
gunzip -c $dbfile >> $tmpfile1
echo "SET foreign_key_checks = 1;" >> $tmpfile1

# Import pre-processed file
echo "Importing pre-processed file $tmpfile1"
if [ "$USE_SOCKET" == "1" ]; then
    cat $tmpfile1 | mariadb "$dbname"
else
    cat $tmpfile1 | mariadb --host "$MARIADB_HOST" --user "$MARIADB_ROOT_USER" --password="$MARIADB_ROOT_PASSWORD" "$dbname"
fi
RV="$?"

rm $tmpfile1
echo "DB_CONNECTION='mysql://$dbuser:$dbpass@$dbhost/$dbname'"
echo "Done! Exiting with code $RV"
exit $RV
