#!/bin/bash

psql -c 'SELECT datname, COUNT(*) FROM pg_stat_activity GROUP BY datname ORDER BY COUNT(*) DESC;'
psql -c 'SELECT SUM(c) FROM (SELECT COUNT(*) as c FROM pg_stat_activity GROUP BY datname ORDER BY COUNT(*) DESC) as tmp;'
