#!/bin/bash

export THIS_SCRIPT=$(basename "$0")
export THIS_PATH=$(dirname `realpath "$0"`)

if [ "$#" -ne 1 ]; then
    echo 'Dumps PostgreSQL database to <dbname>.sql.gz file. Usage:'
    echo 'pg-dump <dbname>'
    exit 1
fi

pg_dump $1 | gzip > $1.sql.gz
exit "$?"
