#!/bin/bash

export THIS_SCRIPT=$(basename "$0")
export THIS_PATH=$(dirname `realpath "$0"`)
export PG_HBA_FILE="/etc/postgresql/`$THIS_PATH/pg-major-ver`/main/pg_hba.conf"

if [ ! -f "$PG_HBA_FILE" ]; then
    echo "$PG_HBA_FILE does not exist. Different PostgreSQL version installed?"
    exit 1
fi

if [ "$#" -ne 2 ]; then
    echo "This script renames both DB and DB user with the same name"
    echo "Usage: $THIS_SCRIPT <old_name> <new_name>"
    exit 1
fi

export OLD_NAME="$1"
export NEW_NAME="$2"

psql -c "SELECT pg_terminate_backend (pid) FROM pg_stat_activity WHERE datname = '$OLD_NAME'"
if [ "$?" != "0" ]; then
    echo "Terminating sessions failed, exiting with 1"
    exit 1
fi

psql -c "ALTER DATABASE $OLD_NAME RENAME TO $NEW_NAME"
if [ "$?" != "0" ]; then
    echo "Renaming DB failed, exiting with 1"
    exit 1
fi

psql -c "ALTER USER $OLD_NAME RENAME TO $NEW_NAME"
if [ "$?" != "0" ]; then
    echo "Renaming DB user failed, exiting with 1"
    exit 1
fi

echo "Rename $OLD_NAME to $NEW_NAME in\nnano $PG_HBA_FILE\nsudo systemctl restart postgresql"
exit $?
