#!/bin/bash

export THIS_SCRIPT=$(basename "$0")
export THIS_PATH=$(dirname `realpath "$0"`)

if [ "$#" -ne 2 ]; then
    echo 'Destroys and re-creates PostgreSQL database from .sql.gz dump'
    echo "Usage: $THIS_SCRIPT <.sql.gz> <dbname>"
    exit 1
fi

export FILENAME=$1
export DBNAME=$2
export OWNER=$2

psql -c "select pg_terminate_backend(pid) from pg_stat_activity where datname='$DBNAME';"
createuser $OWNER
dropdb $DBNAME
createdb $DBNAME -O $OWNER
gunzip -c $FILENAME | psql $DBNAME
if [ "$?" != "0" ]; then
    echo "gunzip -c $FILENAME | psql $DBNAME failed, exiting with 1"
    exit 1
fi
psql -c "ALTER TABLE $DBNAME OWNER TO $OWNER" $DBNAME

exit $?
