#!/bin/bash

export S2=pgdb2

if [ -z "$2" ]; then
  echo "Transfers DB to new DB server $S2"
  echo "Usage: pg-transfer <db> <password>"
  exit
fi

$HOME/pg-dump $1
scp $1.sql.gz $S2:.
ssh $S2 "./pg-import $1 $2"
