#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: ssh-refresh-host <hostname>"
    exit 1
fi

IP="`getent hosts $1 | awk '{ print $1 }'`"
ssh-keygen -R "$IP"
ssh-keyscan -H "$IP" >> ~/.ssh/known_hosts
