#!/bin/bash

apt install -y xvfb

cat > /etc/systemd/system/xfvb99.service <<- "EOF"
[Unit]
Description=X Virtual Frame Buffer Service 99
After=network.target

[Service]
ExecStart=/usr/bin/Xvfb :99 -screen 0 1600x1200x24

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable xfvb99
systemctl start xfvb99
systemctl status xfvb99

apt install firefox -y

