- hosts: servers
  become: yes
  tasks:
  - name: enable nginx sites
    ansible.builtin.file:
      path: "/etc/nginx/sites-enabled/{{ item.domain }}.conf"
      state: link
      src: "/etc/nginx/sites-available/{{ item.domain }}.conf"
    loop: "{{ services }}"
  - name: reload nginx
    ansible.builtin.service:
      name: "nginx"
      state: reloaded
