- hosts: all
  become: yes
  tasks:

  # fail2ban
  - name: install fail2ban
    ansible.builtin.apt:
      name: fail2ban
  - name: setup custom config for fail2ban
    ansible.builtin.template:
      src: '../templates/jail.local.j2'
      dest: "/etc/fail2ban/jail.local"
  - name: restart fail2ban
    ansible.builtin.service:
      name: fail2ban
      state: restarted
      enabled: yes

  # auditd
  - name: install auditd
    ansible.builtin.apt:
      name: auditd
  - name: tweak auditd config (1)
    ansible.builtin.lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: '^{{ item }}\s*=.+$'
      state: absent
    loop:
      - max_log_file
      - num_logs
  - name: tweak auditd config (2)
    ansible.builtin.lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: '^{{ item.key }}\s*=\s*{{ item.value }}$'
      line: "{{ item.key }} = {{ item.value }}"
      state: present
    loop:
      - key: max_log_file
        value: 10
      - key: num_logs
        value: 720

  # disable root login
  - name: disable root ssh login (1)
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin\s+.+$'
      state: absent
  - name: disable root ssh login (2)
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin no$'
      line: "PermitRootLogin no"
      state: present
