- hosts: all
  gather_facts: false
  tasks:

    - name: Scan and save all SSH host keys
      delegate_to: localhost
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan ' + inventory_hostname) }}"

