- hosts: all
  gather_facts: false
  tasks:

    - name: Set custom SSH port fact (or use default)
      delegate_to: localhost
      set_fact:
        ansible_ssh_port: "{{ hostvars[inventory_hostname]['ansible_ssh_port'] | default('22') }}"

    - name: Scan and save all SSH host keys
      delegate_to: localhost
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -p' + ansible_ssh_port + ' ' + inventory_hostname) }}"

