- hosts: db_servers
  become: yes
  tasks:

# postgres
  - name: install postgresql
    ansible.builtin.apt:
      name: postgresql
  - name: install postgis
    ansible.builtin.apt:
      name: "postgresql-{{ pg_major_ver }}-postgis-{{ postgis_major_ver }}, postgresql-contrib postgresql-client-common postgis binutils libproj-dev gdal-bin"
    when: postgis_major_ver is defined

# ufw baseline for db server
- name: ufw baseline
  import_playbook: setup-ufw-db.yml
