- hosts: all
  become: yes
  tasks:

  - name: ufw allow ssh
    community.general.ufw:
      rule: allow
      port: ssh
  - name: ufw allow https
    community.general.ufw:
      rule: allow
      port: https
  - name: ufw allow http
    community.general.ufw:
      rule: allow
      port: http
  - name: ufw default deny
    community.general.ufw:
      default: deny
      direction: incoming
  - name: ufw enable
    community.general.ufw:
      state: enabled
